-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Vært: 127.0.0.1:3306
-- Genereringstid: 23. 10 2023 kl. 13:47:40
-- Serverversion: 8.0.31
-- PHP-version: 8.0.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `webshop`
--

-- --------------------------------------------------------

--
-- Struktur-dump for tabellen `produkter`
--

DROP TABLE IF EXISTS `produkter`;
CREATE TABLE IF NOT EXISTS `produkter` (
  `bogID` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `bogNavn` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `bogBeskrivelse` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `bogPris` decimal(8,2) NOT NULL,
  `bogBillede` varchar(100) DEFAULT NULL,
  `bogDato` date DEFAULT NULL,
  `bogType` varchar(20) NOT NULL,
  `bogForfatter` varchar(50) NOT NULL,
  `bogKategori` varchar(50) NOT NULL,
  `bogForlag` varchar(50) NOT NULL,
  `bogISBN` bigint NOT NULL,
  PRIMARY KEY (`bogID`)
) ENGINE=MyISAM AUTO_INCREMENT=122 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Data dump for tabellen `produkter`
--

INSERT INTO `produkter` (`bogID`, `bogNavn`, `bogBeskrivelse`, `bogPris`, `bogBillede`, `bogDato`, `bogType`, `bogForfatter`, `bogKategori`, `bogForlag`, `bogISBN`) VALUES
(102, 'Den brændende bro', '<p>Skyggen og hans hjælpere forbereder sig på et opgør med den onde krigsherre Morgarath. Will og hans kammerat Horace bliver sendt af sted i et ærinde til det nærliggende Celtica, men byen er forladt og indbyggerne forsvundet. Det viser sig, at det er Lykkedes Morgarath at bringe sine tropper over de barske østlige bjerge, og de truer nu kongens hær. Kun Will og Horace har mulighed for at forpurre Morgaraths onde planer.</p>', '179.95', 'DenBrændendeBro.JPG', '2006-11-17', 'Hæfte', 'John Flanagan', 'Fantasy', 'Gyldendal', 9788721027629),
(103, 'Det vinterfrosne land', '<p>Skyggens lærling Will og pigen Evanlyn er på vej til Skandia som fanger på den frygtindgydende kaptajn Eraks ulveskib. Halt har svoret at ville befri Will, og han vil gøre hvad som helst for at holde sit løfte - endog trodse sin egen konge. Ridderlærlingen Horace slutter sig til ham på hans rejse op gennem Gallica mod Skandia. Undervejs bliver de konstant udfordret af enlige riddere, som ikke er andet end en flok tyvagtige banditter. Men Horace er ikke helt dum til tvekamp, og han begynder snart at tiltrække sig uønsket opmærksomhed fra riddere og krigsherrer i miles omkreds på grund af sine fænomenale færdigheder. Men vil de nå frem i tide til at frelse Will og et liv i trældom?</p>', '179.95', 'DetVinterfrosneLand.webp', '2007-03-05', 'Hæfte', 'John Flanagan', 'Fantasy', 'Gyldendal', 9788721029838),
(101, 'Gorlans ruiner', '<p>Fantasy-serie, som udspilles i et middelalderligt univers. Will kommer som 15 årig i lære hos Skyggen, som arbejder i det skjulte for kongens efterretningstjeneste. For at klare opgaverne og bekæmpe de onde kræfter, som truer kongen, kræves mod, kløgt, hurtighed og snedighed. Følg Will og hans tro væbnere på deres mange farefulde eventyr.Will har altid været lidt bange for dem. Rangerne. For de virker mystiske og gådefulde i deres mørke kapper. Og så har han hørt, at de kan gøre sig usynlige, når de selv vil. 15-årige Will kan ikke komme ind på ridderskolen, fordi han ikke er høj nok. I stedet bliver han tilbudt en læreplads hos Skyggen for at blive uddannet som ranger. Will har de egenskaber, der skal til, siger man. Han er hurtig, han kan bevæge sig lydløst, han kan klatre, og han er skarpsindig. Men han får også brug for at være modig. For Morgarath, herre over Regn- og Nattebjergene, er ved at samle sine frygtindgydende tropper til et angreb mod kongeriget. </p>', '179.95', 'GorlansRuiner.JPG', '2006-10-16', 'Hæfte', 'John Flanagan', 'Fantasy', 'Gyldendal', 9788721027612),
(104, 'Pagten med Skandierne', '<p>Will og Evanlyn bliver tilbageholdt af skandierne og planlægger at flygte fra dem, når foråret kommer. Men Evanlyn bliver bortført af Temujai-krigere, Will sætter efter, men en enlig Ranger-lærling kan ikke hamle op med seks barske krigere.Fantasy-serie, som udspilles i et middelalderligt univers. Will kommer i lære hos Skyggen, som arbejder i det skjulte for kongens efterretningstjeneste. For at klare opgaverne og bekæmpe de onde kræfter, som truer kongen, kræves mod, kløgt, hurtighed og snedighed.</p>', '179.95', '8869-0-800-546.webp', '2007-01-11', 'Hæfte', 'John Flanagan', 'Fantasy', 'Gyldendal', 9788721030933),
(105, 'Troldmanden i Nord', '<p>Der er gået hele 5 år siden aftalen mellem skandierne og arulaerne blev lavet. Will er udlært ranger og nu skal han passe sit helt område, men det går ikke så let som forventet. En mystisk og farlig trolddom lurer nemlig i skyggerne, og Will får store udfordringer med at opklare hvad der foregår. Heldigvis har han sin veninde Alyss til at hjælpe sig.</p>', '179.95', 'TroldmandenINord.jpg', '2008-04-16', 'Hæfte', 'John Flanagan', 'Fantasy', 'Gyldendal', 9788721031183),
(107, 'Harry Potter og De Vises Sten', '<p>Harry fylder 11 år og får en nyhed, som han ikke lige havde forventet. Han er forældreløs, bor hos sin onkel og tante og lever i det hele taget et surt og trist liv - men det er kun lige indtil der begynder at dukke breve op. Så ændrer alting sig.\r\n</p>', '299.95', 'DeVisesSten.JPG', '2020-11-06', 'Indbundet', 'J. K. Rowling', 'Fantasy, Ungdomsbøger', 'Gyldendal', 9788702301588),
(108, 'Harry Potter og Fangen fra Azkaban', '<p>Nu er den farlige straffefange flygtet, og det forlyder, at han er en yderst dedikeret tilhænger af Lord Voldemort. Ifølge vagterne i Azkaban var Black ofte blevet hørt mumle i søvne: “… han er på Hogwarts … han er på Hogwarts …”.  Alt tyder på, at Harry Potter er i fare, selv bag Hogwarts’ tykke mure omgivet af venner. For det viser sig, at der er en forræder iblandt dem…</p>', '399.95', 'FlugtenFraAzkaban.JPG', '2023-10-13', 'Indbundet', 'J. K. Rowling', 'Fantasy, Ungdomsbøger', 'Gyldendal', 9788702397116),
(109, 'Harry Potter og Hemmelighedernes Kammer', '<p>Efter en rædsom sommer hos familien Dursley vender Harry tilbage til Hogwarts for at fortsætte sin troldmandsuddannelse. Men forude venter atter et dramatisk skoleår. Nogle skræmmende og uforklarlige angreb finder sted på skolen, og Harry hvirvles ind i opklaringen af et dystert mysterium om et hemmeligt kammer og et gruopvækkende uhyre...</p>', '299.95', 'HemmelighedernesKammer.JPG', '2021-10-29', 'Indbundet', 'J. K. Rowling', 'Fantasy, Ungdomsbøger', 'Gyldendal', 9788702319361),
(110, 'Lysets Våben', '<p>Med den selvstændige roman \"Lysets våben\" vender Ken Follett tilbage til Kingsbridge med en eminent fortælling om grådighed, lidenskab og had i en verden under dramatiske forandringer.</p>\r\n\r\n<p>Traditioner bliver udfordret, den sociale sammenhængskraft eksploderer og Europas krige knuser håbet om fred. Den industrielle revolution buldrer frem i Kingsbridge og efterlader arbejderne uden arbejde, mens oprøret ulmer. Samtidig forbederer Napoleon sig på at overtage verden – koste hvad det vil. Verden er i brand, og vores hovedpersoner sætter alt ind for at redde Kingsbridges fremtid.\r\n</p>', '269.95', 'LysetsVåben.JPG', '2023-09-26', 'Indbundet', 'Ken Follett', 'Historisk roman', 'Cicero', 9788702399134),
(111, 'Efterforsket - Drabschefens sager', '<p>Personlig beretning om efterforskning af nogle af Danmarks mest spektakulære forbrydelser.\r\n</p>\r\n\r\n<p>Den tidligere drabschef Jens Møller Jensen fortæller om nogle af de mest tragiske og dramatiske kriminalsager, han har været tæt på som garvet efterforsker – sager om alt fra røveri, brand og terror til vold, voldtægter og drab.</p>', '269.95', 'Efterforsket.JPG', '2023-10-12', 'Indbundet', 'Stine Bolther & Jens Møller Jensen', 'Biografi, sande fortællinger, forbrydelser', 'Politikens Forlag', 9788740062519),
(112, 'De hvide nætter', '<p>En tidlig forårsmorgen vågner teenagepigen Shirin i et telt på øen Vorsø ved Horsens Fjord. Hendes storebror sover stadig. Hun står op, går ned til vandkanten og vasker sig i havvandet. Stranden er øde, og der er alt for stille. Deres far, Tami, ville vække dem tidligt, så de kunne fiske fra morgenstunden, men nu står solen allerede højt på himlen. Hun går hen til farens telt for at vække ham, men finder ham med halsen skåret over, badet i sit eget blod. Han er død.</p>', '179.95', 'DeHvideNætter.JPG', '2023-10-10', 'E-bog', 'Katrine Engberg', 'Krimi', 'Alpha Forlag', 9788775622832),
(113, 'Vanedyr', '<p>Undervejs får du indsigt i, hvordan verdens førende virksomheder udnytter deres viden om menneskets instinkt og biologi til at skabe en form for afhængighedsskabende superstimuli, det er svært at bryde ud af. Men forstår du, hvordan hjernen fungerer, kan du vinde kontrollen tilbage, og det gør du efter endt læsning af \"Vanedyr\".\r\n</p>\r\n\r\n<p>Vi er opslugt af meningsløst indhold på alverdens skærme. Vi indtager junk og sukker. Og vi ved det er forkert. At vi burde ændre vores adfærd. Men hvorfor er det så svært at slippe fri af de usunde vaner? Det giver Nicklas et underholdende, kritisk og videnskabeligt svar på i \"Vanedyr\".</p>\r\n\r\n<p>\r\nUndervejs får du indsigt i, hvordan verdens førende virksomheder udnytter deres viden om menneskets instinkt og biologi til at skabe en form for afhængighedsskabende superstimuli, det er svært at bryde ud af. Men forstår du, hvordan hjernen fungerer, kan du vinde kontrollen tilbage, og det gør du efter endt læsning af \"Vanedyr\".</p>', '259.95', 'Vanedyr.JPG', '2023-10-10', 'Indbundet', 'Nicklas Brendborg', 'Medicin, sundhed, sygdom', 'Grønningen', 9788773392225),
(114, 'Nærmest fri', '<p>I Nærmest fri– min vej ud af mørket tager han læseren med på rejsen, fra han trådte ud i friheden efter 13 måneder som gidsel. Fra dette første skridt begyndte en ny overlevelseskamp, den universelle kamp for at finde sig til rette imellem den, man er, den andre ser, og den man gerne vil være. Gang på gang har han troet, at han havde lagt fortiden bag sig for så igen at blive revet tilbage. Til sidst konfronterede han sig selv og sin historie.</p>\r\n\r\n<p>I sommeren 2022 tog fotografen Daniel Rye til Washington for at se en af sine torturbødler i øjnene. Turen satte en eksplosion af tanker i gang og blev kulminationen på den indre rejse, han har været på, siden Islamisk Stat frigav ham. På den ene side ville han videre – leve et normalt liv, skabe en familie. På den anden side skulle han se sine traumer i øjnene, forholde sig til efterretningstjenesters spørgsmål og besøge sine medfangers efterladte.</p>', '249.95', 'NærmestFri.JPG', '2023-09-14', 'Hæfte', 'Daniel Rye', 'Biografi', 'Politikens Forlag', 9788740083941),
(115, 'ADHD på jobbet', '<p>Mange voksne med adhd klarer sig fint på arbejdsmarkedet, mens andre kan have en række udfordringer. Men med den rette viden og i nogle tilfælde en vis tilpasning behøver adhd ikke at være en forhindring for at få et godt, indholdsrigt og meningsfyldt arbejdsliv.</p>\r\n\r\n<p>I bogen beskriver de to forfatter de udfordringer, voksne med adhd typisk oplever på en arbejdsplads, og de kommer med en række gode råd til hvilke strategier, man kan vælge for at overvinde udfordringerne, og den støtte, arbejdspladsen kan give. De gennemgår ligeledes den nyeste forskning på området. Det hele suppleres med en række cases fra en hverdag med adhd på jobbet – fortalt af nogle af de mennesker, de to har mødt i deres klinik.</p>', '299.95', 'ADHDpåJobbet.JPG', '2023-08-18', 'Hæfte', 'Lotta Borg Skoglund & Martina Nelson', 'Psykologi, sundhe', 'Forlaget Pressto Aps', 9788793716827),
(116, 'Sapiens - En kort historie om menneskeheden', '<p>For 100.000 år siden var vor klode beboet af minimum seks forskellige menneskearter. I dag er der kun én tilbage - os. Hvad skete der med de andre arter? Og hvad vil der måske ske med os?\r\n\r\nDe fleste bøger om menneskehedens historie har enten en historisk eller en biologisk tilgang til emnet, men i sin bog \"Sapiens\" bryder Dr. Yuval Noah Harari mønstret. Denne ekstremt originale bog begynder for omkring 70.000 år siden med fremkomsten af moderne kognition. Fra at udforske den rolle udviklende mennesker har spillet i det globale økosystem til at kortlægge imperiernes opståen, integrerer \"Sapiens - A Brief History of Humankind\" historie og videnskab i sin mission om at genoverveje accepterede narrativer, sammenknytte tidligere udviklinger med nutidige problematikker og at undersøge specifikke hændelser i kontekst af større idéer.</p>', '199.95', 'homosapiens.JPG', '2023-01-30', 'Hæfte', 'Yuval Noah Harari', 'Naturvidenskab, historie', 'Lindhardt og Ringhof', 9788711568873),
(117, 'Giftig gæld og udpint velfærd', '<p>Denne bog udstiller med talrige eksempler et udpint dansk velfærdssamfund, hvor bl.a. sundheds- og uddannelsessystem lider af socialt, tidsligt og økonomisk underskud. Med udgangspunkt i grundig forskning, viser lektor i Ledelse, organisation og arbejdsliv, Susanne Ekman, hvor svært det er for både ledere og medarbejdere i velfærdsstatens maskineri at adressere systemiske problemer, især når det gælder misforhold mellem krav og ressourcer. I stedet lander ansvaret hos den enkelte, som føler krav om at overbyde i forhold til tid og ressourcer. I bogen anskues denne dynamik som en radikal individualisering, hvor det næsten bliver umuligt at etablere ændringer, som har en større systemisk effekt. I stedet skruer og doktorerer man på individets arbejdsomhed, ansvarsforståelse, overbudsvillighed, selvledelsespraksis og robusthed.  Dette understøtter tendensen til at se kollaps (både individers og organisationers) som undtagelsestilstande, der ikke kræver systemiske ændringer. Når vi ser situationen som en undtagelsestilstand, kræver det tilsyneladende blot, at vi får dét individ eller dén organisation på benene igen – gerne med de samme midler, der rent faktisk bidrog til kollapset i sin tid, herunder lovsang af robusthed, selvledelse og ansvar for egen sygdom. Som ideologi er individualismen svær at udfordre, fordi den fletter sig kompliceret sammen med selvrealiseringsidealet og følelsen af at have ’ret’ til at være noget særligt i arbejdssammenhæng.Susanne Ekman har skrevet en aktuel og virkelighedsnær debatbog om den danske velfærdsstats udfordringer og krise. En bog, som uden tvivl vil vække debat og opmærksomhed i den danske offentlighed – både blandt politikere, praktikere og helt almindelige danskere. </p>', '279.95', 'GiftifGæld.JPG', '2022-06-02', 'Hæfte', 'Susanne Ekman', 'Samfund', 'Gyldendal', 9788702333480),
(118, 'Jytte fra Marketing er desværre gået for i dag', '<p>Mennesker i den virkelige verden opfører sig sjældent som de mennesker, vi bygger strategier til. De gør ikke, som vi har planlagt, de skal gøre. Faktisk modarbejder vi menneskets biologi og psykologi, når vi insisterer på, at gode argumenter, brændende platforme, klassisk change management, pjecer, kampagner og fællesmøder er vejen frem.\r\n</p>\r\n\r\n<p>\r\nI \"Jytte fra Marketing er desværre gået for i dag\" omsætter Morten Münster de seneste 40 års forskning i menneskers adfærd til en lettilgængelig metode i fire trin - og giver en håndsrækning til alle ledere og medarbejdere, der leder efter alternativer til de gængse virkemidler. \r\n</p>\r\n\r\n<p>\r\n\"Jytte fra Marketing er desværre gået for i dag\" giver dig en evidensbaseret tilgang til at ændre adfærd, der vil hjælpe dig til at skabe forandringer i den virkelige verden.</p>', '119.95', 'JyttefraMarketing.JPG', '2017-09-18', 'E-bog', 'Morten Münster', 'Ledelse, adfærd, økonomi', 'Gyldendal Business', 9788702243581),
(119, 'AT TÆNKE - hurtigt og langsomt', '<p>Daniel Kahneman giver os i At tænke - hurtigt og langsomt  et unikt indblik i den menneskelige bevidsthed og i de to systemer, som driver den måde, vi tænker på: System 1 er hurtigt, intuitivt og følelsesdrevet; System 2 er langsomt, rationelt og logisk. Ved at trække på erfaringerne fra eksperimenter foretaget gennem et helt liv afslører Daniel Kahneman, hvornår vi kan stole på den hurtige tænknings intuition, og hvordan vi kan drage fordel af den langsomme tænkning. Han giver praktisk og oplysende indsigt i, hvordan valg træffes i både vores professionelle og private liv - og hvordan vi kan bruge forskellige teknikker som værn mod de mentale faldgruber, der ofte skaffer os i vanskeligheder. At tænke - hurtigt og langsomt  vil for altid forandre den måde, du oplever verden og træffer beslutninger på.</p>', '299.95', 'AtTænke.JPG', '2018-04-26', 'Hæfte', 'Daniel Kahneman', 'Naturvidenskab', 'Lindhardt og Ringhof', 9788711533284),
(120, 'Støj - Sådan træffer du bedre beslutninger', '<p>”Støj - Sådan træffer du bedre beslutninger\" er Daniel Kahneman, Cass R. Sunstein og Olivier Sibonys nye bog om at blive bedre til at tage beslutninger og lære at lukke for den ydre støj, der kan ødelægge din beslutningsproces.</p>\r\n\r\n<p>Med ”Støj - Sådan træffer du bedre beslutninger” bliver du i stand til at identificere de faktorer, der skaber støj omkring dig, og hvordan du lukker dem ude. Bogen er fuld af praktiske eksempler, ny forskning og forskellige casestudier, der underbygger det, som Daniel Kahneman, Cass R. Sunstein og Olivier Sibonys introducerer undervejs. Bogen henvender sig både til ansatte i det offentlige og private, men også til almindelige mennesker, der ønsker at blive bedre til at træffe beslutninger.\r\n</p>', '349.95', 'Støj.JPG', '2021-05-26', 'Indbundet', 'Olivier Sibony, Daniel Kahneman & Cass R. Sunstein', 'Psykologi, sundhed', 'Lindhardt og Ringhof', 9788711902721),
(121, 'Omgivet af idioter', '<p>\"Omgivet af idioter\" er Thomas Eriksons internationale bestseller om vores personlighedstyper, der giver dybere indsigt i hvem du og dine omgivelser er.</p>\r\n\r\n<p>\r\nThomas Erikson giver med en dyb videnskabelig forankring indsigt i hvem du er som type, og hvilke både negative og positive egenskaber du besidder. Typerne er farveinddelt, og du vil med garanti kunne genkende dig selv og dine omgivelser i farverne. Er du måske ”rød”, styrende og målbevidst? Eller analytisk som de ”blå”? Undervejs får du en række konkrete værktøjer til at forstå andre mennesker endnu bedre ud for deres personlighedstype, og reducerer dermed risikoen for den ødelæggende dårlige kommunikation.</p>', '199.95', 'OmgivetafIdioter.JPG', '2022-01-27', 'Hæfte', 'Thomas Erikson', 'Psykologi, sundhed', 'Hoi Forlag', 9788793853959);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
